---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    domain: grupafestiwale.pl
    tailscale_network: 100.64.0.0/10

  children:
    proxmox:
      hosts:
        pve-hetzner:
          ansible_host: "{{ vault_proxmox_ip }}"
          ansible_port: 22

    lxc:
      children:
        lxc_vault:
          hosts:
            lxc-00-vault:
              ansible_host: 10.10.60.7
              proxmox_vmid: 100
              vlan: 60
        lxc_core:
          hosts:
            lxc-01-core:
              ansible_host: 10.10.10.2
              proxmox_vmid: 101
              vlan: [10, 20]
        lxc_db:
          hosts:
            lxc-02-db:
              ansible_host: 10.10.30.3
              proxmox_vmid: 102
              vlan: 30
        lxc_data:
          hosts:
            lxc-03-data:
              ansible_host: 10.10.30.4
              proxmox_vmid: 103
              vlan: 30
        lxc_auth:
          hosts:
            lxc-06-auth:
              ansible_host: 10.10.10.8
              proxmox_vmid: 106
              vlan: [10, 20]

    vm:
      children:
        vm_ai_prod:
          hosts:
            vm-04-ai-prod:
              ansible_host: 10.10.40.5
              proxmox_vmid: 104
              vlan: 40
        vm_dev:
          hosts:
            vm-05-dev:
              ansible_host: 10.10.50.6
              proxmox_vmid: 105
              vlan: 50
