---
- name: restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true
